### ISSUE TITLE
DRACO JSON to RC?

### ISSUE THREAD

**Issue by cnk113** [dincarnato/RNAFramework#12]
Hello,

I was wondering how you converted the JSON output from DRACO into the RC format as mentioned in your DRACO paper?

Thanks,
Chang

**Comment by dincarnato** [comment]
Dear Chang,

Many thanks for your request.
I am currently working to a new module, rf-json2rc that will allow to do that.
For the DRACO paper we wrote a tailored code using the RNA Framework APIs.
I hope to finish the new module in a couple of days.

I'll notify you then.

Best,
Danny

**Comment by dincarnato** [comment]
Dear Chang,

thanks for your patience. It took a bit longer than I originally expected.
The new version of RNA Framework (2.7.1) is now available, and it includes the **rf-json2rc** module for converting DRACO JSON output files into RC files.
For a detailed description of the algorithm, please refer to the [docs](https://rnaframework-docs.readthedocs.io/en/latest/rf-json2rc/).

Please let me know if you have any questions, otherwise i will close the issue.
Hope this will help!

All the best,
Danny

**Comment by dincarnato** [comment]
Dear Chang,

I did not hear from you.
I assume you had the chance to test the rf-json2rc module? Can I close the issue?

Many thanks!
Best,

Danny

**Comment by cnk113** [comment]
Sorry for the late followup it works fine on my data.

**Comment by dincarnato** [comment]
Dear Chang,

No worries. Glad to hear it works.
I'll close the issue.

Best,
Danny
