### ISSUE TITLE
rf-map statistics showing poor mapping_ion torrent read compatibility

### ISSUE THREAD

**Issue by adiroy92** [dincarnato/RNAFramework#36]
Hi Danny,
I am Aditya from India. I am a great fan of RNAFramework for its simplicity and very useful documentation. However, i am facing some issues. Those are following:
1. We have sequenced the NAI treated and untreated mRNA sample by preparing a cDNA library following ion torrent's Ion Total RNA-Seq Kit v2 manual as our platform is Ion PROTON. When I have mapped the raw fastq reads using rf-map command ($ rf-map -b2 -cp -bi hg38_refGene treated.fastq untreated.fastq --bowtie2; and its index), in summary statistics after mapping, its showing the following statistics similar to both the samples : [ Mapped: 13.78%; Failed: 36.88%; Multiple: 49.34%]. Does that mean only 13.78% of the total reads were mapped to the human genome (hg38). WHY does most of the reads have been discarded?
2. 
3. When I have prompted Ion Torrent Suite software (comes with the sequencer) for mapping however, it mapped 90% of the reads using STAR followed by Bowtie2 for unmapped reads. I tried to use that .bam file for mutation counting, but failed due to some EOF header issue or truncation in the .bam file.What is happening here?

Your expert suggestions on these matters are highly appreciated. Than you.

**Comment by dincarnato** [comment]
Hi,

Your reads are not being discarded, they simply have multiple mapping positions.
You can use STAR and then feed the resulting BAM files into rf-count directly, if you prefer, without passing through rf-map.

The second issue seems to be linked to the fact that your BAM file is truncated or corrupted. What happens if you do "samtools view yourfile.bam"? Do you get an EOF error? If not, can you please share the BAM file with me so that I can replicate the issue?

Best,
Danny

**Comment by dincarnato** [comment]
Also, please paste the EXACT error you get. I cannot figure out what happens without clear error messages.
