### ISSUE TITLE
rf-jackknife: Can't locate object method "structure"

### ISSUE THREAD

**Issue by kuntzagk** [dincarnato/RNAFramework#6]
Hi,

when I try to run rf_jackknife I get the following error:

```
user@server ~]$ rf-jackknife -r Ecoli_reference.fasta -x -rp "-nlp -md 600" ribozero_norm

[+] Making output directory...
[+] Checking input reference structures and probing data [0 imported]Can't locate object method "structure" via package "Data::Sequence" at /mypath/rf-jackknife line 234, <$fh> line 61.

What am I doing wrong here?
```
PERL5LIB is set to /mypath/lib/

**Comment by dincarnato** [comment]
Dear Andreas,

I will make an educated guess here.
I think that you are passing as the "reference" (via the -r parameter) a regular fasta file, containing only the sequence of the Ecoli RNAs. What rf-jackknife expects instead is a file containing a set of reference structures, in dot-bracket notation.
Something like:

>transcript1
AAAAAAAACCCCUUUUUUUU
((((((((....))))))))
>transcript2
AAACCCUUUCCCUUUGGG
(((...)))(((...)))

The program is crashing because there is no structure in your Ecoli_reference.fasta.
Please let me know if this solves the issue.
Best,

Danny

**Comment by kuntzagk** [comment]
Ok, I see. 

Would I need to create the reference structures myself? 
(sorry, I'm only a SysAdmin tasked with installing RNAFramework and not a bioinformatician)

**Comment by dincarnato** [comment]
Hi Andreas,

I understand, no worries!
No, the structures are known... but there is no "repository" of known structures included in RNAFramework. I will include in in a future release.
Can you please send me the ecoli_reference.fasta file you are using, so that I known what sequences are in there? Maybe I have a couple of reference structures I can give you to test it.

Danny

**Comment by dincarnato** [comment]
Hi Andreas,

Can I close the issue?

Danny

**Comment by kuntzagk** [comment]
Hi Danny,


sorry for not getting back to you. Yes please close the issue.

Thanks for your support.


regards, Andreas

________________________________
